In [30]:
#import packages
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import confusion_matrix

In [4]:
#import data
spam_df = pd.read_csv('spam.csv')

In [6]:
spam_df.groupby('Category').describe()


Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [7]:
spam_df['spam']=spam_df['Category'].apply( lambda x: 1 if x=='spam' else 0 )

In [8]:
spam_df


Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [10]:
x_train , x_test , y_train , y_test =train_test_split(spam_df.Message ,spam_df.spam)

In [11]:
x_train

5042    She ran off with a younger man. we will make p...
5436                           Mode men or have you left.
2196    V-aluable. A-ffectionate. L-oveable. E-ternal....
3946    I will be gentle princess! We will make sweet ...
4398                               When did dad get back.
                              ...                        
2527       Do u noe how 2 send files between 2 computers?
4248    Text PASS to 69669 to collect your polyphonic ...
864     Did u find out what time the bus is at coz i n...
4683                Haha yeah, 2 oz is kind of a shitload
553     Sure, if I get an acknowledgement from you tha...
Name: Message, Length: 4179, dtype: object

In [13]:
cv = CountVectorizer()
x_train_count = cv.fit_transform(x_train.values)

In [18]:
x_train_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [19]:
model = MultinomialNB()
model.fit(x_train_count , y_train)

MultinomialNB()

In [24]:
email_ham = ['click money reward ']
email_ham_count =cv.transform(email_ham)
model.predict(email_ham_count)

array([0], dtype=int64)

In [39]:
x_test_count = cv.transform(x_test)
model.score(x_test_count , y_test)
nb_y_prediction = model.predict(x_test_count)


In [38]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(x_train_count,y_train)
lr.score(x_test_count , y_test)

0.9820531227566404

In [33]:
from sklearn.metrics import confusion_matrix 
lr_y_prediction = lr.predict(x_test_count)

In [35]:
cm_lr = confusion_matrix(y_test,lr_y_prediction )
cm_nb=confusion_matrix(y_test,nb_y_prediction)

In [36]:
cm_lr

array([[1213,    4],
       [  21,  155]], dtype=int64)

In [37]:
cm_nb

array([[1213,    4],
       [  17,  159]], dtype=int64)

# we calculate metrics for logistic regression lr

In [53]:
tnlr , fplr , fnlr,tplr = cm_lr.ravel()

In [54]:
tnlr , fnlr

(1213, 21)

In [55]:
accuracy = (tnlr+tplr)/(tnlr+tplr+fnlr+fplr)

In [56]:
accuracy

0.9820531227566404

In [57]:
sensitivity =tplr/(tplr+fnlr)
sensitivity

0.8806818181818182

In [58]:
specificity =tnlr/(tnlr+fplr)
specificity

0.9967132292522597

In [65]:
precision = tplr/(tplr+fplr)
precision

0.9748427672955975

In [66]:
npv=tnlr/(tnlr+fnlr)
npv

0.9829821717990276

# metrics for naive bayes

In [59]:
tnnb , fpnb , fnnb,tpnb = cm_nb.ravel()

In [60]:
accuracynb = (tnnb+tpnb)/(tnnb+tpnb+fnnb+fpnb)

In [61]:
sensitivitynb =tpnb/(tpnb+fnnb)
sensitivitynb

0.9034090909090909

In [62]:
specificitynb =tnnb/(tnnb+fpnb)
specificitynb

0.9967132292522597

In [67]:
precisionnb = tpnb/(tpnb+fpnb)
precisionnb

0.9754601226993865

In [72]:
npvnb=tnnb/(tnnb+fnnb)
npvnb

0.9861788617886179